#language:pt

@login_bit
Funcionalidade: testes no SSO Hero

Cenário: login
* irei logar no bit    

Esquema do Cenário: Inserir manualmente no bit bucket

Dado que estou logado 
Quando entrar com <contas> 
Então implantar

Exemplos:

|                contas               |
|           "cepibge2sqlite"          |
|           "fs-foundation"           |
|          "integracaonextel"         |
|          "project-skeleton"         |
|            "q-processor"            |
|    "cofre-milionario-versao-dois"   |
|             "antirroubo"            |
|           "antirrouboj2me"          |
|     "aplicativoagregadorandroid"    |
|    "aplicativoagregadorwindowspc"   |
|           "integracao_tim"          |
|            "smartbilling"           |
|       "automatizacaotestephp"       |
|             "autostart"             |
|              "backend"              |
|             "blacklist"             |
|         "blacklist_nextgen"         |
|         "blacklist-service"         |
|       "brasiltec_app_afazenda"      |
|       "brasiltec_app_aprendiz"      |
|      "brasiltec_app_brasiltec"      |
|     "brasiltec_app_burgermania"     |
|     "brasiltec_app_certificado"     |
|    "brasiltec_app_correiodopovo"    |
|      "brasiltec_app_eaidoutor"      |
|      "brasiltec_app_edirmacedo"     |
|      "brasiltec_app_eduguedes"      |
|     "brasiltec_app_fabioarruda"     |
|        "brasiltec_app_idolos"       |
|         "brasiltec_app_jump"        |
|      "brasiltec_app_loveschool"     |
|     "brasiltec_app_pecadomortal"    |
|     "brasiltec_app_r7olimpiadas"    |
|    "brasiltec_app_recordlondres"    |
|      "brasiltec_callcentervivo"     |
|        "brasiltec_historico"        |
|        "brasiltec_lp_record"        |
|         "brasiltec_lp_vivo"         |
|      "brasiltec_site_afazenda"      |
|      "brasiltec_site_facafesta"     |
|   "brasiltec_site_foliadepremios"   |
|     "brasiltec_site_goldecraque"    |
|   "brasiltec_site_premiosdeverao"   |
|       "brasiltec_site_reports"      |
|     "brasiltec_site_reports_cdr"    |
|    "brasiltec_site_sorteemdobro"    |
|    "brasiltec_site_viradadasorte"   |
|   "brasiltec_site_votacaopremiada"  |
|             "broadcast"             |
|     "businessintelligencebrtec"     |
|        "businessintelligence"       |
|     "businessintelligencefsvas"     |
|           "microstrategy"           |
|              "timdash"              |
|              "vivodash"             |
|                "cal"                |
|                 "bu"                |
|           "camada_sdp_pu"           |
|          "campaign-unified"         |
|    "delivery-sat-push-plataform"    |
|                "enfe"               |
|       "gerenciadoroperacional"      |
|            "luckynumber"            |
|             "oauth-omh"             |
|  "oi-recarga-luckynumber-generate"  |
|     "plataformasegurancanextel"     |
|            "provisioner"            |
|                "qbe"                |
|              "research"             |
|             "rowing-nfe"            |
|                "suc"                |
|                "cdc"                |
|          "interfacesnextel"         |
|        "centraldecomunicacao"       |
|            "cloudvision"            |
|           "cofatvivofixa"           |
|          "comissionamento"          |
|       "comissionamentoseguros"      |
|               "compra"              |
|       "corebasefrontendnextel"      |
|         "corebasefrontendoi"        |
|                "ctbc"               |
|              "hotsite"              |
|          "unifiedplatform"          |
|        "static-workflow-core"       |
|          "crongvtsoslegado"         |
|                 "cs"                |
|              "cslight"              |
|               "cspom"               |
|              "csutils"              |
|         "algarbackuponline"         |
|                "ctbc"               |
|            "ctbcseguros"            |
|        "dbwrappercallcenter"        |
|          "demodicicomapfre"         |
|   "designportalvendassegurancatim"  |
|              "devnull"              |
|                 "dm"                |
|               "dm_old"              |
|   "documentacaotecnicaoperadoras"   |
|             "hero-core"             |
|            "hero-vipcard"           |
|              "embedded"             |
|                "erp"                |
|             "experience"            |
|               "fsvas"               |
|           "fsvaswebdriver"          |
|        "games-autentication"        |
|          "gatewayminutrade"         |
|          "gatewaypuresight"         |
|             "api-vendor"            |
|         "backend-unificado"         |
|            "cancel-tool"            |
|             "cepibge2db"            |
|    "cofre-milionario-versao-dois"   |
|           "df-repository"           |
|            "lucky-router"           |
|      "processamento-vivo-fixa"      |
|         "request_queue_gvt"         |
|          "reset-state-vivo"         |
|               "sso-db"              |
|         "genericzendmodules"        |
|      "gerenciadoroperacionaloi"     |
|             "globalsdp"             |
|            "gns_seguros"            |
|            "mailgateway"            |
|             "filhos-web"            |
|           "designfrontend"          |
|            "gvtpomsites"            |
|             "hub_brand"             |
|          "hub_public_store"         |
|           "apis_producao"           |
|             "chef-repo"             |
|           "ctbc_producao"           |
|           "infraestrutura"          |
|              "fit_prod"             |
|          "fsadmin_producao"         |
|            "gvt_producao"           |
|               "infra"               |
|          "livetim_producao"         |
|          "nextel_producao"          |
|            "oi_producao"            |
|            "r7_producao"            |
|               "sdp-mo"              |
|            "sdp_producao"           |
|           "sdp-vivo-cron"           |
|              "sdp_vivo"             |
|              "sdp-vivo"             |
|           "tasa_producao"           |
|         "timkidscriar_prod"         |
|            "tim_producao"           |
|          "varejo_producao"          |
|            "vfs_producao"           |
|         "vivoclubekids_prod"        |
|         "vivolojas_producao"        |
|           "vivo_producao"           |
|            "internalapis"           |
|              "intranet"             |
|               "infra"               |
|              "keymaker"             |
|            "lp-seguranca"           |
|             "vivo-lojas"            |
|          "vivosync-mobile"          |
|            "livronanuvem"           |
|    "lojaspropriassegurancanextel"   |
|      "lojaspropriassegurancaoi"     |
|            "lojastimweb"            |
|          "lojavarejofsvas"          |
|         "luckynumbersender"         |
|            "hero-backend"           |
|        "hosite-loja-fastshop"       |
|              "hotsite"              |
|              "pomhero"              |
|   "designportalvendassegurancatim"  |
|          "managerresultns"          |
|            "manageruser"            |
|    "blacklist-integration-tests"    |
|            "blacklist-v3"           |
|              "pomhero"              |
|            "billing-tim"            |
|            "billing-vivo"           |
|            "site-pom-tim"           |
|                "misp"               |
|        "clube-criar-backend"        |
|        "clube-criar-frontend"       |
|            "integracaoba"           |
|         "importadorfastshop"        |
|     "importadormaquinadevendas"     |
|          "importadornextel"         |
|           "importadorqbe"           |
|      "backend-seguros-endpoint"     |
|            "fraseologia"            |
|          "integracaoalgar"          |
|         "integracaointerna"         |
|          "integracaomapfre"         |
|           "integracaotim"           |
|           "integracaovivo"          |
|         "interatividadesms"         |
|        "luckynumbermediator"        |
|          "recargareceiver"          |
|        "renew-expired-sales"        |
|    "seguros-billing-integration"    |
|    "seguros-client-communication"   |
|          "seguros-pre-sale"         |
|        "vivoprocessadoremail"       |
|          "vivoprocessador"          |
|           "movistarchile"           |
|    "cofre-milionario-versao-dois"   |
|          "nextelgatewayapi"         |
|           "nextelgateway"           |
|          "gatewaypuresight"         |
|              "gwmcafee"             |
|            "oigatewaymo"            |
|            "oigatewaymt"            |
|           "nextelgateway"           |
|         "portalfunambolvivo"        |
|         "promo-android-app"         |
|           "promo-ios-app"           |
|            "partnersapis"           |
|  "plataformaaprovisionamentochaves" |
|   "plataformaassistenciaunificado"  |
|          "integracaonexel"          |
|            "landingpage"            |
|        "nextelintegrationapi"       |
|              "pomhero"              |
|       "plataformanumerosorte"       |
|      "plataformasegurancactbc"      |
|       "plataformasegurancagvt"      |
|  "plataformasegurancamovistarchile" |
|     "plataformasegurancanextel"     |
|     "plataformasegurancaoifixa"     |
|       "plataformasegurancar7"       |
|    "plataformasegurancavivofixa"    |
|         "vivo-agregador-web"        |
|         "websitevivomeuguru"        |
|     "plataformasegurounificado"     |
|    "plataformavendassegurancar7"    |
|"plataformavendassegurancatelefonica"|
| "plataformavendassegurancatimfiber" |
|   "plataformavendassegurancavivo"   |
|         "pom-oi-app-android"        |
|           "pom-oi-app-ios"          |
|            "pomservices"            |
|       "portabilidadenumerica"       |
|      "portalassistenciagvtsos"      |
|             "sitegvtsos"            |
|     "portalassistenciaunificado"    |
|     "portalatendimentoqualidade"    |
|               "portal"              |
|         "portalfunambolgvt"         |
|       "portalfunambolmovistar"      |
|        "portalfunambolnextel"       |
|       "portalfunambolterabox"       |
|       "sitemigracaovsyncvivo"       |
|    "portalmapfresegurosunificado"   |
|        "portalvendasseguros"        |
|      "portalvendassegurancatim"     |
|       "portalvendasseguroctbc"      |
|      "portalvendassegurogvtsos"     |
|       "portalvendassegurotim"       |
|       "portalvendassegurovivo"      |
|              "positivo"             |
|         "promocaoasorteesua"        |
|          "promocaocampeao"          |
|   "PromocaoCofreMilionarioLegacy"   |
|        "rihappy-fs-platform"        |
|       "promocaofestadepremios"      |
|            "mandapremios"           |
|         "promocaoodiaehoje"         |
|              "psm_old"              |
|                "psm"                |
|              "reports"              |
|            "hotsitehero"            |
|              "rps_old"              |
|                "rps"                |
|          "satpush-backend"          |
|          "vivo_tela_preta"          |
| "scriptatendimentomapfresegurosvivo"|
|            "securityhub"            |
|              "bilogger"             |
|        "servicoautenticacao"        |
|          "importador-algar"         |
|        "simuladorvendashero"        |
|              "sistema"              |
|        "sitemapfresegurostim"       |
|       "sitemapfresegurosvivo"       |
|         "SiteSegurancaClaro"        |
|        "sitesegurancanextel"        |
|          "sitesegurancatim"         |
|         "sitevivoclubekids"         |
|            "smartbilling"           |
|             "smsmanager"            |
|              "smsteste"             |
|                "sso"                |
|        "subscriptionservice"        |
|              "suc_old"              |
|                "suc"                |
|                "sugf"               |
|                "tasa"               |
|             "vivo-lojas"            |
|           "base-leveling"           |
|             "broadcast"             |
|          "campaign-router"          |
|         "ephemeral-barrier"         |
|        "microservice-commons"       |
|         "UnifiedPlatformNG"         |
|                "t2m"                |
|          "unifiedplatform"          |
|           "unifiedRouter"           |
|       "unifiedsubscriptionapi"      |
|             "utilities"             |
|               "varejo"              |
|               "velip"               |
|         "vitrinetimprotect"         |
|            "vitrinevivo"            |
|        "claroclubecriarhtml"        |
|          "integracaocaixa"          |
|           "wordpress-core"          |
|      "wordpress-promo-history"      |
